export const HARDWARE_KEY = 'c10b96ad-4d2c-4c1d-b932-ba022566e840';
export const NANO_ID = 'zvX9xMXpNkqCmVFzSa10keVH';
export const FIRMWARE_VERSION = '1.0.3';
export const CONFIG_FILE_NAME = 'config.txt';
export const FIRMWARE_FILE_NAME = 'firmware.txt';
export const COMMAND_FILE_NAME = 'command-log.txt';
export const STD_LOG_FILE = 'out.log';
export const ERR_LOG_FILE = 'err.log';
export const TURNED_OFF_FILE_NAME = 'TURNED_OFF_OK.txt';
export const DEVICE_PROVISIONING_SERVER = 'http://localhost:3000';
export const DEVICE_PROVISIONING_PROXY = 'http://proxy.xyte.local';
export const INTERVAL_IN_MS = 10 * 1000; // How often to send telemetry (in milliseconds)
