export const HARDWARE_KEY = 'cb04432e-b465-4f08-a50d-9881b71aceab';
export const NANO_ID = '123412341234';
export const FIRMWARE_VERSION = '1.0.0';
export const CONFIG_FILE_NAME = 'config.txt';
export const FIRMWARE_FILE_NAME = 'firmware.txt';
export const COMMAND_FILE_NAME = 'command-log.txt';
export const STD_LOG_FILE = 'out.log';
export const ERR_LOG_FILE = 'err.log';
export const TURNED_OFF_FILE_NAME = 'TURNED_OFF_OK.txt';
export const DEVICE_REGISTRATION_SERVER = 'https://entry.xyte.io';
export const INTERVAL_IN_MS = 10 * 1000; // How often to send telemetry (in milliseconds)
